function changeText(){
    document.getElementById("menu1").innerHTML=("Start");
    document.getElementById("menu2").innerHTML=("Tips");
    document.getElementById("menu3").innerHTML=("Know about us");
    document.getElementById("cuenta").innerHTML=("Login/Create Account");
    document.getElementById("pregunta1").innerHTML=("What do we Propose?");
    document.getElementById("parrafo1").innerHTML=("A web page aimed at solving the problem of child illiteracy, since in El Salvador there are more than 800,000 boys and girls who are not part of the student population, who for many reasons could not continue with their studies, our web page is a service free that all boys and girls can enter with the help of their parents, a platform for 5-year-olds, with topics appropriate to their age, with extensive information and interactivity, with games that motivate the child to continue learning the topics provided by each unit. Likewise, parents have a call to dedicate time to the education of their children, so that their learning is optimal and they can resolve any doubts with them. Parents who always lend their children their cell phones should lend them to them with this platform, so that the child learns new things, the help of a responsible adult is also needed for a better understanding of the child.");
    document.getElementById("pregunta2").innerHTML=("What do we Propose?");
    document.getElementById("parrafo2").innerHTML=("We think of the idea of our website from one of the greatest concerns in our country, education. And even more so after these hard times, during and after a global pandemic, we focus on a public that suffered and suffers, 5-year-old children, in addition to being the public most likely to suffer neglect in their educational process. With this platform we offer them essential topics in their cognitive development that otherwise could not mature. Some reasons why these boys and girls could not have an adequate study process is the economic scarcity on the part of the parents, school desertion, and the responsibility of the parents when it comes to educating their children, in addition to the state of the current infrastructure of schools and colleges nationwide.");
    document.getElementById("pregunta3").innerHTML=("What do we Propose?");
    document.getElementById("parrafo3").innerHTML=("We are a company that seeks to create an accessible education page for all children in the country, who for some reason do not have the opportunity to study and go to school like other children. As a company we want to create a virtual education platform, a free page where children can learn with the topics taught in each unit, with the help of a parent or their responsible adult they can study as if it were a student center and carry out interactive activities so that they can have fun while they learn, parents will also have an exclusive section on tips and advice to help the child have a better learning process.");  
    document.getElementById("foter").innerHTML=("2022 SEI. All rights reserved.");
}